---
title: "Chapter 3"
fig_caption: yes
output:
  pdf_document: 
    keep_tex: true
---

Loading the required libraries (R studio will warn you about non-installed libraries)


```{r load_libraries}
library(tidyverse)
library(knitr)
library(qqplotr)
library(reshape2)
library(factoextra)
library(FactoMineR)
library(caret)
library(multcomp)
```

Create a simulated dataset for showing correlation of variables

```{r spurious_correlation, fig.width=4, fig.height=4}
set.seed(123)
spurious_data <- data.frame(x = rnorm(500, 10, 1),
                            y = rnorm(500, 9, 1),
                            z = rnorm(500, 30, 6))
cor(spurious_data$x, spurious_data$y)
plot(spurious_data$x, spurious_data$y)

#same data divided for variable Z

ratio_xz <- spurious_data$x / spurious_data$z
ratio_yz <- spurious_data$y / spurious_data$z 
cor(ratio_xz,ratio_yz)
plot(ratio_xz,ratio_yz)



```

```{r ex3_plots, fig.width=4, fig.height=4}
load(file = "E:/temp/test/ESMAM-main/El_extend.RData")
asphalt.pca <- PCA((Ag1[3:length(Ag1)]),
                   graph = FALSE, 
                   scale.unit = FALSE)
#if you t want to scale just change scale.unit = TRUE
var2 <- get_pca_var(asphalt.pca)
print(var2$contrib,digits=3)
fviz_pca_ind(asphalt.pca, 
             col.ind=as.factor(marble.origin),
             repel=TRUE) + xlim(c=-5,5)+ylim(-5,5)
fviz_pca_var(asphalt.pca, col.var = "black",repel = TRUE)
fviz_eig(asphalt.pca, addlabels = TRUE ,ylim = c(0, 100),
         repel = TRUE) +theme_bw()
fviz_pca_biplot(asphalt.pca,
                col.ind=as.factor(marble.origin),
                repel = TRUE)+ xlim(c=-5,5)+ylim(-5,5)
```

#Create dendogram

```{r,ex3_dendogram,  fig.width=5, fig.height=4}
#change your path according to your system
load(file = "C:/temp/Marble.RData")
library(dendextend)
df.norep.noclass.scaled <- Ag1[3:length(Ag1)]
#load data 
dend <- df.norep.noclass.scaled %>%
        dist %>% hclust %>% as.dendrogram 
#number of cluster choosen k=3
dend %>% plot
dend %>% rect.dendrogram(k=3, border = 8, lty = 5, lwd = 2)
```

#Linear Discriminant Analysis performed splitting in a training set and test set 80/20

```{r,ex3_lda3,  fig.width=4, fig.height=4}
set.seed(123)
training.samples <- df.rep.scaled$myclass %>% 
  createDataPartition(p = 0.8, list = FALSE)
train.data <- df.rep.scaled[training.samples, ]
test.data <- df.rep.scaled[-training.samples, ]
preproc.param <- train.data %>% 
  preProcess(method = c("center", "scale"))
train.transformed <- preproc.param %>% predict(train.data)
test.transformed <- preproc.param %>% predict(test.data)
model <- lda(myclass~., data = train.transformed)
# Make predictions
predictions <- model %>% predict(test.transformed)
# Model accuracy
mean(predictions$class==test.transformed$myclasses)
lda.data <- cbind(train.transformed, predict(model)$x)
model
```


```{r ex3_mda_1, echo=FALSE, message=FALSE, warning=FALSE,  fig.width=5, fig.height=5}
library(mda)
# Fit the model

model.mda <- mda(myclass~., data = train.transformed)
model.mda
# Make predictions
predicted.classes <- model %>% predict(test.transformed)
# Model accuracy
mean(predicted.classes == test.transformed$Species)

#plot based on 
#https://stats.stackexchange.com/
##         /questions/143692/plotting-qda-projections-in-r

library(klaR)
partimat(myclass ~ ., data = df.rep.scaled[c(1:4,11)],
         method = "qda", plot.matrix = TRUE,
         col.correct='green', col.wrong='red')
partimat(myclass ~ ., data = df.rep.scaled[c(5:8,11)],
         method = "qda", plot.matrix = TRUE,
         col.correct='green', col.wrong='red')
partimat(myclass ~ ., data = df.rep.scaled[c(9:10,11)],
         method = "qda", plot.matrix = TRUE,
         col.correct='green', col.wrong='red')

```


```{r ex_mda_2, echo=FALSE, message=FALSE, warning=FALSE,fig.width=5, fig.height=5}
library(mda)
# Fit the model
model.mda <- mda(myclass~., data = train.transformed)
model.mda
# Make predictions
predicted.classes <- model %>% predict(test.transformed)
# Model accuracy
mean(predicted.classes == test.transformed$Species)

#plot based on 
# https://stats.stackexchange.com/
#           /questions/143692/plotting-qda-projections-in-r

library(klaR)
partimat(myclass ~ ., data = df.rep.scaled[c(1:4,11)],
         method = "qda", plot.matrix = TRUE,
         col.correct='green', col.wrong='red')
partimat(myclass ~ ., data = df.rep.scaled[c(5:8,11)],
         method = "qda", plot.matrix = TRUE,
         col.correct='green', col.wrong='red')
partimat(myclass ~ ., data = df.rep.scaled[c(9:10,11)],
         method = "qda", plot.matrix = TRUE,
         col.correct='green', col.wrong='red')

```


```{r ex3_simca, echo=FALSE, message=FALSE, warning=FALSE,  fig.width=5, fig.height=5}
library(mda)
library(mdatools)
library(data.table)
# Fit the model
#model class A
df.rep.sort <- df.rep.scaled[order(myclass),]
df.rep.sort <- data.table(df.rep.sort)
data = df.rep.sort[, 1:10]
class = df.rep.sort[, 11]

#in order to sort the class to model
Am = (df.rep.sort[myclass=="A"])[,1:10]
# make SIMCA model and apply to test set
model = simca(Am, 'A', cv = 1)
model = selectCompNum(model, 1)
# show infromation, summary and plot overview
print(model)
summary(model)
plot(model)

```


```{r  ch3_simca_models, echo=FALSE, message=FALSE, warning=FALSE,  fig.width=5, fig.height=5}
library(mdatools)


df.rep.sort <- df.rep.scaled[order(myclass),]
df.rep.sort <- data.table(df.rep.sort)

idx = seq(1, nrow(df.rep.sort), by = 1)
Xc = df.rep.sort[idx, 1:10]
cc = df.rep.sort[idx, 11]

Xt = df.rep.sort[-idx, 1:10]
Ct = df.rep.sort[-idx, 11]

data = df.rep.sort[idx, 1:10]

class = df.rep.sort[idx, 11]
X.A = (df.rep.sort[myclass=="A"])[,1:10]

class = df.rep.sort[, 11]
X.M = (df.rep.sort[myclass=="M"])[,1:10]

class = df.rep.sort[, 11]
X.T = (df.rep.sort[myclass=="T"])[,1:10]

modelA = simca(X.A, 'A', cv = 1)
modelA = selectCompNum(modelA,4)
#perform SIMCA modelling and apply it to  a test set

print(modelA)
summary(modelA)
plot(modelA)


```
